-- Bronze landing tables for raw CSV data
DEFINE TABLE COCO_DE_DEMO.BRONZE.CUSTOMERS (
    CUSTOMER_ID NUMBER,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    EMAIL VARCHAR,
    PHONE VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    ZIP_CODE VARCHAR,
    SEGMENT VARCHAR,
    CREATED_AT TIMESTAMP_NTZ
)
CHANGE_TRACKING = TRUE
DATA_METRIC_SCHEDULE = '60 MINUTE'
COMMENT = 'Raw customer profiles from S3';

DEFINE TABLE COCO_DE_DEMO.BRONZE.ORDERS (
    ORDER_ID NUMBER,
    CUSTOMER_ID NUMBER,
    ORDER_DATE DATE,
    STATUS VARCHAR,
    SALES_CHANNEL VARCHAR,
    TOTAL_AMOUNT NUMBER(12,2)
)
CHANGE_TRACKING = TRUE
DATA_METRIC_SCHEDULE = '60 MINUTE'
COMMENT = 'Raw order headers from S3';

DEFINE TABLE COCO_DE_DEMO.BRONZE.ORDER_ITEMS (
    ORDER_ITEM_ID NUMBER,
    ORDER_ID NUMBER,
    PRODUCT_ID NUMBER,
    QUANTITY NUMBER,
    UNIT_PRICE NUMBER(10,2),
    DISCOUNT NUMBER(5,2)
)
CHANGE_TRACKING = TRUE
DATA_METRIC_SCHEDULE = '60 MINUTE'
COMMENT = 'Raw order line items from S3';

DEFINE TABLE COCO_DE_DEMO.BRONZE.PRODUCTS (
    PRODUCT_ID NUMBER,
    PRODUCT_NAME VARCHAR,
    CATEGORY VARCHAR,
    SUBCATEGORY VARCHAR,
    BRAND VARCHAR,
    LIST_PRICE NUMBER(10,2),
    COST_PRICE NUMBER(10,2),
    STOCK_QUANTITY NUMBER
)
CHANGE_TRACKING = TRUE
DATA_METRIC_SCHEDULE = '60 MINUTE'
COMMENT = 'Raw product catalog from S3';

DEFINE TABLE COCO_DE_DEMO.BRONZE.PAYMENTS (
    PAYMENT_ID NUMBER,
    ORDER_ID NUMBER,
    PAYMENT_METHOD VARCHAR,
    AMOUNT NUMBER(12,2),
    PAYMENT_DATE DATE,
    STATUS VARCHAR
)
CHANGE_TRACKING = TRUE
DATA_METRIC_SCHEDULE = '60 MINUTE'
COMMENT = 'Raw payment records from S3';

DEFINE TABLE COCO_DE_DEMO.BRONZE.SHIPMENTS (
    SHIPMENT_ID NUMBER,
    ORDER_ID NUMBER,
    CARRIER VARCHAR,
    TRACKING_NUMBER VARCHAR,
    SHIP_DATE TIMESTAMP_NTZ,
    DELIVERY_DATE TIMESTAMP_NTZ,
    STATUS VARCHAR
)
CHANGE_TRACKING = TRUE
DATA_METRIC_SCHEDULE = '60 MINUTE'
COMMENT = 'Raw shipment tracking from S3';

-- Profiling output table
DEFINE TABLE COCO_DE_DEMO.BRONZE.DATA_PROFILE_LOG (
    PROFILE_RUN_ID VARCHAR,
    TABLE_NAME VARCHAR,
    COLUMN_NAME VARCHAR,
    METRIC VARCHAR,
    METRIC_VALUE VARCHAR,
    PROFILED_AT TIMESTAMP_NTZ
)
COMMENT = 'Bronze data profiling results';
