-- Custom Data Metric Functions

-- Custom DMF: Validates amounts are positive
DEFINE DATA METRIC FUNCTION COCO_DE_DEMO.BRONZE.DMF_POSITIVE_AMOUNTS(
    TABLE_NAME TABLE(COLUMN_VALUE NUMBER)
)
RETURNS NUMBER
AS
$$
    SELECT COUNT(*)
    FROM TABLE_NAME
    WHERE COLUMN_VALUE < 0
$$;

-- Custom DMF: Referential integrity between orders and customers
DEFINE DATA METRIC FUNCTION COCO_DE_DEMO.BRONZE.DMF_ORDER_CUSTOMER_INTEGRITY(
    TABLE_NAME TABLE(COLUMN_VALUE NUMBER)
)
RETURNS NUMBER
AS
$$
    SELECT COUNT(*)
    FROM TABLE_NAME t
    LEFT JOIN COCO_DE_DEMO.BRONZE.CUSTOMERS c ON t.COLUMN_VALUE = c.CUSTOMER_ID
    WHERE c.CUSTOMER_ID IS NULL
      AND t.COLUMN_VALUE IS NOT NULL
$$;

-- Attach system DMFs to Bronze tables

-- CUSTOMERS
ATTACH DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT
    TO TABLE COCO_DE_DEMO.BRONZE.CUSTOMERS
    ON (CUSTOMER_ID)
    EXPECTATION NO_NULL_CUSTOMER_IDS (value = 0);

ATTACH DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT
    TO TABLE COCO_DE_DEMO.BRONZE.CUSTOMERS
    ON (CUSTOMER_ID)
    EXPECTATION NO_DUPLICATE_CUSTOMER_IDS (value = 0);

-- ORDERS
ATTACH DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT
    TO TABLE COCO_DE_DEMO.BRONZE.ORDERS
    ON (ORDER_ID)
    EXPECTATION NO_NULL_ORDER_IDS (value = 0);

ATTACH DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT
    TO TABLE COCO_DE_DEMO.BRONZE.ORDERS
    ON (ORDER_ID)
    EXPECTATION NO_DUPLICATE_ORDER_IDS (value = 0);

ATTACH DATA METRIC FUNCTION COCO_DE_DEMO.BRONZE.DMF_POSITIVE_AMOUNTS
    TO TABLE COCO_DE_DEMO.BRONZE.ORDERS
    ON (TOTAL_AMOUNT)
    EXPECTATION ALL_AMOUNTS_POSITIVE (value = 0);

ATTACH DATA METRIC FUNCTION COCO_DE_DEMO.BRONZE.DMF_ORDER_CUSTOMER_INTEGRITY
    TO TABLE COCO_DE_DEMO.BRONZE.ORDERS
    ON (CUSTOMER_ID)
    EXPECTATION ALL_ORDERS_HAVE_CUSTOMERS (value = 0);

-- ORDER_ITEMS
ATTACH DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT
    TO TABLE COCO_DE_DEMO.BRONZE.ORDER_ITEMS
    ON (ORDER_ITEM_ID)
    EXPECTATION NO_NULL_ORDER_ITEM_IDS (value = 0);

ATTACH DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT
    TO TABLE COCO_DE_DEMO.BRONZE.ORDER_ITEMS
    ON (ORDER_ITEM_ID)
    EXPECTATION NO_DUPLICATE_ORDER_ITEM_IDS (value = 0);

-- PRODUCTS
ATTACH DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT
    TO TABLE COCO_DE_DEMO.BRONZE.PRODUCTS
    ON (PRODUCT_ID)
    EXPECTATION NO_NULL_PRODUCT_IDS (value = 0);

ATTACH DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT
    TO TABLE COCO_DE_DEMO.BRONZE.PRODUCTS
    ON (PRODUCT_ID)
    EXPECTATION NO_DUPLICATE_PRODUCT_IDS (value = 0);

-- PAYMENTS
ATTACH DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT
    TO TABLE COCO_DE_DEMO.BRONZE.PAYMENTS
    ON (PAYMENT_ID)
    EXPECTATION NO_NULL_PAYMENT_IDS (value = 0);

ATTACH DATA METRIC FUNCTION COCO_DE_DEMO.BRONZE.DMF_POSITIVE_AMOUNTS
    TO TABLE COCO_DE_DEMO.BRONZE.PAYMENTS
    ON (AMOUNT)
    EXPECTATION ALL_PAYMENT_AMOUNTS_POSITIVE (value = 0);

-- SHIPMENTS
ATTACH DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT
    TO TABLE COCO_DE_DEMO.BRONZE.SHIPMENTS
    ON (SHIPMENT_ID)
    EXPECTATION NO_NULL_SHIPMENT_IDS (value = 0);

ATTACH DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT
    TO TABLE COCO_DE_DEMO.BRONZE.SHIPMENTS
    ON (SHIPMENT_ID)
    EXPECTATION NO_DUPLICATE_SHIPMENT_IDS (value = 0);
