-- Gold enrichment output tables (managed by Snowpark procedures)
DEFINE TABLE COCO_DE_DEMO.GOLD.CUSTOMER_RFM_SCORES (
    CUSTOMER_ID NUMBER,
    RECENCY_SCORE NUMBER,
    FREQUENCY_SCORE NUMBER,
    MONETARY_SCORE NUMBER,
    RFM_SEGMENT VARCHAR,
    SCORED_AT TIMESTAMP_NTZ
)
COMMENT = 'RFM scoring for customer segmentation';

DEFINE TABLE COCO_DE_DEMO.GOLD.PIPELINE_RUN_SUMMARY (
    RUN_ID VARCHAR,
    LAYER VARCHAR,
    TABLE_NAME VARCHAR,
    ROW_COUNT NUMBER,
    RUN_TIMESTAMP TIMESTAMP_NTZ
)
COMMENT = 'Pipeline execution summary with row counts by layer';
