-- Silver output tables for anomaly detection
DEFINE TABLE COCO_DE_DEMO.SILVER.ANOMALY_FLAGS (
    ANOMALY_ID VARCHAR,
    TABLE_NAME VARCHAR,
    RECORD_ID VARCHAR,
    ANOMALY_TYPE VARCHAR,
    DETAILS VARCHAR,
    DETECTED_AT TIMESTAMP_NTZ
)
COMMENT = 'Anomalies detected in Silver data';
