-- Silver output tables for anomaly detection
DEFINE TABLE COCO_DE_DEMO.SILVER.ANOMALY_FLAGS (
    ANOMALY_ID NUMBER AUTOINCREMENT,
    DETECTED_AT TIMESTAMP_NTZ,
    ANOMALY_TYPE VARCHAR,
    TABLE_NAME VARCHAR,
    RECORD_ID NUMBER,
    FIELD_NAME VARCHAR,
    FIELD_VALUE VARCHAR,
    THRESHOLD VARCHAR,
    DESCRIPTION VARCHAR
)
DATA_METRIC_SCHEDULE = '60 MINUTE'
COMMENT = 'Anomalies detected in Silver data';
