-- Pipeline orchestration DAG (8 tasks)
-- All tasks in DCM schema to separate orchestration from data layers

-- Task 1: Root task - validates Bronze data, triggers on stream activity
DEFINE TASK COCO_DE_DEMO.DCM.TSK_VALIDATE_BRONZE
USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
SCHEDULE = '1 MINUTE'
COMMENT = 'Root task: validates Bronze data quality (Gate 1)'
WHEN SYSTEM$STREAM_HAS_DATA('COCO_DE_DEMO.BRONZE.STR_CUSTOMERS')
    OR SYSTEM$STREAM_HAS_DATA('COCO_DE_DEMO.BRONZE.STR_ORDERS')
    OR SYSTEM$STREAM_HAS_DATA('COCO_DE_DEMO.BRONZE.STR_ORDER_ITEMS')
    OR SYSTEM$STREAM_HAS_DATA('COCO_DE_DEMO.BRONZE.STR_PRODUCTS')
    OR SYSTEM$STREAM_HAS_DATA('COCO_DE_DEMO.BRONZE.STR_PAYMENTS')
    OR SYSTEM$STREAM_HAS_DATA('COCO_DE_DEMO.BRONZE.STR_SHIPMENTS')
AS
CALL COCO_DE_DEMO.BRONZE.SP_VALIDATE_BRONZE();

-- Task 2: Profile Bronze tables
DEFINE TASK COCO_DE_DEMO.DCM.TSK_PROFILE_BRONZE
USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
COMMENT = 'Profiles all Bronze tables'
AFTER COCO_DE_DEMO.DCM.TSK_VALIDATE_BRONZE
AS
CALL COCO_DE_DEMO.BRONZE.SNOWPARK_BRONZE_PROFILER();

-- Task 3: Run dbt Silver models (only if Gate 1 passed)
DEFINE TASK COCO_DE_DEMO.DCM.TSK_RUN_SILVER_DBT
USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'SMALL'
COMMENT = 'Runs dbt Silver models if Gate 1 passed'
AFTER COCO_DE_DEMO.DCM.TSK_VALIDATE_BRONZE
AS
CALL COCO_DE_DEMO.SILVER.SP_RUN_DBT_SILVER();

-- Task 4: Detect anomalies in Silver data
DEFINE TASK COCO_DE_DEMO.DCM.TSK_DETECT_ANOMALIES
USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
COMMENT = 'Detects anomalies in Silver data'
AFTER COCO_DE_DEMO.DCM.TSK_RUN_SILVER_DBT
AS
CALL COCO_DE_DEMO.SILVER.SNOWPARK_ANOMALY_DETECTOR();

-- Task 5: Validate Silver data (Gate 2)
DEFINE TASK COCO_DE_DEMO.DCM.TSK_VALIDATE_SILVER
USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
COMMENT = 'Validates Silver data quality (Gate 2)'
AFTER COCO_DE_DEMO.DCM.TSK_DETECT_ANOMALIES
AS
CALL COCO_DE_DEMO.SILVER.SP_VALIDATE_SILVER();

-- Task 6: Run dbt Gold models (only if Gate 2 passed)
DEFINE TASK COCO_DE_DEMO.DCM.TSK_RUN_GOLD_DBT
USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'SMALL'
COMMENT = 'Runs dbt Gold models if Gate 2 passed'
AFTER COCO_DE_DEMO.DCM.TSK_VALIDATE_SILVER
AS
CALL COCO_DE_DEMO.GOLD.SP_RUN_DBT_GOLD();

-- Task 7: Enrich Gold data with customer scoring
DEFINE TASK COCO_DE_DEMO.DCM.TSK_ENRICH_GOLD
USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
COMMENT = 'Computes RFM scores and pipeline summary'
AFTER COCO_DE_DEMO.DCM.TSK_RUN_GOLD_DBT
AS
CALL COCO_DE_DEMO.GOLD.SNOWPARK_GOLD_ENRICHMENT();

-- Task 8: Certify Gold data (Gate 3)
DEFINE TASK COCO_DE_DEMO.DCM.TSK_CERTIFY_GOLD
USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
COMMENT = 'Certifies Gold data quality (Gate 3)'
AFTER COCO_DE_DEMO.DCM.TSK_ENRICH_GOLD
AS
CALL COCO_DE_DEMO.GOLD.SP_CERTIFY_GOLD();
