-- ============================================================
-- TEARDOWN SCRIPT: Partial reset of COCO_DE_DEMO for demo rebuild
-- Resets pipeline objects but KEEPS: database, schemas, Bronze
-- tables, S3 stage, storage integration, and file format.
-- Usage: snow sql -f teardown.sql -c sfseapac-au_demo70
-- ============================================================

USE ROLE ACCOUNTADMIN;

-- 1. Drop Streamlit app
DROP STREAMLIT IF EXISTS COCO_DE_DEMO.GOLD.DE_PIPELINE_DASHBOARD;

-- 2. Drop dbt project object
DROP DBT PROJECT IF EXISTS COCO_DE_DEMO.DCM.DBT_PIPELINE;

-- 3. Suspend and drop tasks (child tasks first, root task last)
ALTER TASK IF EXISTS COCO_DE_DEMO.DCM.TSK_CERTIFY_GOLD SUSPEND;
ALTER TASK IF EXISTS COCO_DE_DEMO.DCM.TSK_ENRICH_GOLD SUSPEND;
ALTER TASK IF EXISTS COCO_DE_DEMO.DCM.TSK_RUN_GOLD_DBT SUSPEND;
ALTER TASK IF EXISTS COCO_DE_DEMO.DCM.TSK_VALIDATE_SILVER SUSPEND;
ALTER TASK IF EXISTS COCO_DE_DEMO.DCM.TSK_DETECT_ANOMALIES SUSPEND;
ALTER TASK IF EXISTS COCO_DE_DEMO.DCM.TSK_RUN_SILVER_DBT SUSPEND;
ALTER TASK IF EXISTS COCO_DE_DEMO.DCM.TSK_PROFILE_BRONZE SUSPEND;
ALTER TASK IF EXISTS COCO_DE_DEMO.DCM.TSK_VALIDATE_BRONZE SUSPEND;

DROP TASK IF EXISTS COCO_DE_DEMO.DCM.TSK_CERTIFY_GOLD;
DROP TASK IF EXISTS COCO_DE_DEMO.DCM.TSK_ENRICH_GOLD;
DROP TASK IF EXISTS COCO_DE_DEMO.DCM.TSK_RUN_GOLD_DBT;
DROP TASK IF EXISTS COCO_DE_DEMO.DCM.TSK_VALIDATE_SILVER;
DROP TASK IF EXISTS COCO_DE_DEMO.DCM.TSK_DETECT_ANOMALIES;
DROP TASK IF EXISTS COCO_DE_DEMO.DCM.TSK_RUN_SILVER_DBT;
DROP TASK IF EXISTS COCO_DE_DEMO.DCM.TSK_PROFILE_BRONZE;
DROP TASK IF EXISTS COCO_DE_DEMO.DCM.TSK_VALIDATE_BRONZE;

-- 4. Drop pipes
DROP PIPE IF EXISTS COCO_DE_DEMO.BRONZE.PIPE_CUSTOMERS;
DROP PIPE IF EXISTS COCO_DE_DEMO.BRONZE.PIPE_ORDERS;
DROP PIPE IF EXISTS COCO_DE_DEMO.BRONZE.PIPE_ORDER_ITEMS;
DROP PIPE IF EXISTS COCO_DE_DEMO.BRONZE.PIPE_PRODUCTS;
DROP PIPE IF EXISTS COCO_DE_DEMO.BRONZE.PIPE_PAYMENTS;
DROP PIPE IF EXISTS COCO_DE_DEMO.BRONZE.PIPE_SHIPMENTS;

-- 5. Drop streams
DROP STREAM IF EXISTS COCO_DE_DEMO.BRONZE.STR_CUSTOMERS;
DROP STREAM IF EXISTS COCO_DE_DEMO.BRONZE.STR_ORDERS;
DROP STREAM IF EXISTS COCO_DE_DEMO.BRONZE.STR_ORDER_ITEMS;
DROP STREAM IF EXISTS COCO_DE_DEMO.BRONZE.STR_PRODUCTS;
DROP STREAM IF EXISTS COCO_DE_DEMO.BRONZE.STR_PAYMENTS;
DROP STREAM IF EXISTS COCO_DE_DEMO.BRONZE.STR_SHIPMENTS;

-- 6. Drop Gold tables (dbt-created and Snowpark output tables)
DROP TABLE IF EXISTS COCO_DE_DEMO.GOLD.DIM_CUSTOMERS;
DROP TABLE IF EXISTS COCO_DE_DEMO.GOLD.DIM_PRODUCTS;
DROP TABLE IF EXISTS COCO_DE_DEMO.GOLD.DIM_DATES;
DROP TABLE IF EXISTS COCO_DE_DEMO.GOLD.FACT_SALES;
DROP TABLE IF EXISTS COCO_DE_DEMO.GOLD.FACT_DAILY_REVENUE;
DROP TABLE IF EXISTS COCO_DE_DEMO.GOLD.FACT_PAYMENT_SUMMARY;
DROP TABLE IF EXISTS COCO_DE_DEMO.GOLD.FACT_SHIPMENT_PERFORMANCE;
DROP TABLE IF EXISTS COCO_DE_DEMO.GOLD.CUSTOMER_RFM_SCORES;
DROP TABLE IF EXISTS COCO_DE_DEMO.GOLD.PIPELINE_RUN_SUMMARY;

-- 7. Drop Silver tables (dbt-created and Snowpark output tables)
DROP TABLE IF EXISTS COCO_DE_DEMO.SILVER.STG_CUSTOMERS;
DROP TABLE IF EXISTS COCO_DE_DEMO.SILVER.STG_ORDERS;
DROP TABLE IF EXISTS COCO_DE_DEMO.SILVER.STG_ORDER_ITEMS;
DROP TABLE IF EXISTS COCO_DE_DEMO.SILVER.STG_PRODUCTS;
DROP TABLE IF EXISTS COCO_DE_DEMO.SILVER.STG_PAYMENTS;
DROP TABLE IF EXISTS COCO_DE_DEMO.SILVER.STG_SHIPMENTS;
DROP TABLE IF EXISTS COCO_DE_DEMO.SILVER.ANOMALY_FLAGS;

-- 8. Drop Bronze profiling output table (keep raw landing tables)
DROP TABLE IF EXISTS COCO_DE_DEMO.BRONZE.DATA_PROFILE_LOG;

-- 9. Drop stored procedures
DROP PROCEDURE IF EXISTS COCO_DE_DEMO.BRONZE.SP_VALIDATE_BRONZE();
DROP PROCEDURE IF EXISTS COCO_DE_DEMO.BRONZE.SP_PROFILE_BRONZE();
DROP PROCEDURE IF EXISTS COCO_DE_DEMO.BRONZE.VALIDATE_BRONZE_GATE();
DROP PROCEDURE IF EXISTS COCO_DE_DEMO.SILVER.SP_VALIDATE_SILVER();
DROP PROCEDURE IF EXISTS COCO_DE_DEMO.SILVER.SP_RUN_DBT_SILVER();
DROP PROCEDURE IF EXISTS COCO_DE_DEMO.SILVER.VALIDATE_SILVER_GATE();
DROP PROCEDURE IF EXISTS COCO_DE_DEMO.GOLD.SP_CERTIFY_GOLD();
DROP PROCEDURE IF EXISTS COCO_DE_DEMO.GOLD.SP_RUN_DBT_GOLD();
DROP PROCEDURE IF EXISTS COCO_DE_DEMO.GOLD.SP_ENRICH_GOLD();
DROP PROCEDURE IF EXISTS COCO_DE_DEMO.GOLD.VALIDATE_GOLD_GATE();

-- 10. Drop custom Data Metric Functions
DROP FUNCTION IF EXISTS COCO_DE_DEMO.BRONZE.DMF_POSITIVE_AMOUNTS(TABLE(NUMBER));
DROP FUNCTION IF EXISTS COCO_DE_DEMO.BRONZE.DMF_ORDER_CUSTOMER_INTEGRITY(TABLE(NUMBER));

-- 11. Drop tags (DCM schema)
DROP TAG IF EXISTS COCO_DE_DEMO.DCM.PIPELINE_LAYER;
DROP TAG IF EXISTS COCO_DE_DEMO.DCM.DATA_CLASSIFICATION;
DROP TAG IF EXISTS COCO_DE_DEMO.DCM.PII;
DROP TAG IF EXISTS COCO_DE_DEMO.DCM.DATA_DOMAIN;
DROP TAG IF EXISTS COCO_DE_DEMO.DCM.QUALITY_TIER;

-- 12. (Tags are in DCM schema — dropped in step 11 above)

-- 13. Clear dbt stage files (keep the stage itself)
REMOVE @COCO_DE_DEMO.DCM.DBT_STAGE;

-- 14. Drop internal load stage
DROP STAGE IF EXISTS COCO_DE_DEMO.BRONZE.LOAD_STAGE;

-- 15. Drop Streamlit stage
DROP STAGE IF EXISTS COCO_DE_DEMO.GOLD.STREAMLIT_STAGE;

-- ============================================================
-- PRESERVED (not dropped):
--   - Database: COCO_DE_DEMO
--   - Schemas: BRONZE, SILVER, GOLD, DCM
--   - Storage Integration: COCO_DE_DEMO_S3_INT
--   - External Stage: COCO_DE_DEMO.BRONZE.S3_STAGE
--   - File Format: COCO_DE_DEMO.BRONZE.CSV_FORMAT
--   - Bronze landing tables (with data): CUSTOMERS, ORDERS,
--     ORDER_ITEMS, PRODUCTS, PAYMENTS, SHIPMENTS
-- ============================================================

-- Verification: Run these after teardown to confirm state
-- SHOW STAGES IN SCHEMA COCO_DE_DEMO.BRONZE;   -- Should show S3_STAGE only
-- SHOW TABLES IN SCHEMA COCO_DE_DEMO.BRONZE;   -- Should show 6 raw tables only
-- SHOW TABLES IN SCHEMA COCO_DE_DEMO.SILVER;   -- Should return 0 rows
-- SHOW TABLES IN SCHEMA COCO_DE_DEMO.GOLD;     -- Should return 0 rows
-- SHOW TASKS IN DATABASE COCO_DE_DEMO;          -- Should return 0 rows
-- SHOW INTEGRATIONS LIKE 'COCO_DE_DEMO%';      -- Should show S3 integration
