default:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: SFSEAPAC-AU_DEMO70
      user: czhu
      role: ACCOUNTADMIN
      database: COCO_DE_DEMO
      warehouse: COMPUTE_WH
      schema: SILVER
      threads: 4
