-- Post-deployment script: Objects that depend on DEFINE'd entities
-- Run with: snow sql -f post_deploy.sql -c sfseapac-au_demo70

-- External stage (not supported by DEFINE)
CREATE OR REPLACE STAGE COCO_DE_DEMO.BRONZE.S3_STAGE
    STORAGE_INTEGRATION = COCO_DE_DEMO_S3_INT
    URL = 's3://coco-d4bdemo-de/assets/'
    FILE_FORMAT = COCO_DE_DEMO.BRONZE.CSV_FORMAT;

-- CDC Streams on all Bronze tables (not supported by DEFINE)
CREATE OR REPLACE STREAM COCO_DE_DEMO.BRONZE.STR_CUSTOMERS
    ON TABLE COCO_DE_DEMO.BRONZE.CUSTOMERS
    APPEND_ONLY = FALSE
    SHOW_INITIAL_ROWS = TRUE;

CREATE OR REPLACE STREAM COCO_DE_DEMO.BRONZE.STR_ORDERS
    ON TABLE COCO_DE_DEMO.BRONZE.ORDERS
    APPEND_ONLY = FALSE
    SHOW_INITIAL_ROWS = TRUE;

CREATE OR REPLACE STREAM COCO_DE_DEMO.BRONZE.STR_ORDER_ITEMS
    ON TABLE COCO_DE_DEMO.BRONZE.ORDER_ITEMS
    APPEND_ONLY = FALSE
    SHOW_INITIAL_ROWS = TRUE;

CREATE OR REPLACE STREAM COCO_DE_DEMO.BRONZE.STR_PRODUCTS
    ON TABLE COCO_DE_DEMO.BRONZE.PRODUCTS
    APPEND_ONLY = FALSE
    SHOW_INITIAL_ROWS = TRUE;

CREATE OR REPLACE STREAM COCO_DE_DEMO.BRONZE.STR_PAYMENTS
    ON TABLE COCO_DE_DEMO.BRONZE.PAYMENTS
    APPEND_ONLY = FALSE
    SHOW_INITIAL_ROWS = TRUE;

CREATE OR REPLACE STREAM COCO_DE_DEMO.BRONZE.STR_SHIPMENTS
    ON TABLE COCO_DE_DEMO.BRONZE.SHIPMENTS
    APPEND_ONLY = FALSE
    SHOW_INITIAL_ROWS = TRUE;

-- Snowpipe auto-ingest pipes (not supported by DEFINE)
CREATE OR REPLACE PIPE COCO_DE_DEMO.BRONZE.PIPE_CUSTOMERS
    AUTO_INGEST = TRUE
    AS COPY INTO COCO_DE_DEMO.BRONZE.CUSTOMERS
    FROM @COCO_DE_DEMO.BRONZE.S3_STAGE/raw_data_stage/
    PATTERN = '.*customers.*\\.csv';

CREATE OR REPLACE PIPE COCO_DE_DEMO.BRONZE.PIPE_ORDERS
    AUTO_INGEST = TRUE
    AS COPY INTO COCO_DE_DEMO.BRONZE.ORDERS
    FROM @COCO_DE_DEMO.BRONZE.S3_STAGE/raw_data_stage/
    PATTERN = '.*orders[^_].*\\.csv';

CREATE OR REPLACE PIPE COCO_DE_DEMO.BRONZE.PIPE_ORDER_ITEMS
    AUTO_INGEST = TRUE
    AS COPY INTO COCO_DE_DEMO.BRONZE.ORDER_ITEMS
    FROM @COCO_DE_DEMO.BRONZE.S3_STAGE/raw_data_stage/
    PATTERN = '.*order_items.*\\.csv';

CREATE OR REPLACE PIPE COCO_DE_DEMO.BRONZE.PIPE_PRODUCTS
    AUTO_INGEST = TRUE
    AS COPY INTO COCO_DE_DEMO.BRONZE.PRODUCTS
    FROM @COCO_DE_DEMO.BRONZE.S3_STAGE/raw_data_stage/
    PATTERN = '.*products.*\\.csv';

CREATE OR REPLACE PIPE COCO_DE_DEMO.BRONZE.PIPE_PAYMENTS
    AUTO_INGEST = TRUE
    AS COPY INTO COCO_DE_DEMO.BRONZE.PAYMENTS
    FROM @COCO_DE_DEMO.BRONZE.S3_STAGE/raw_data_stage/
    PATTERN = '.*payments.*\\.csv';

CREATE OR REPLACE PIPE COCO_DE_DEMO.BRONZE.PIPE_SHIPMENTS
    AUTO_INGEST = TRUE
    AS COPY INTO COCO_DE_DEMO.BRONZE.SHIPMENTS
    FROM @COCO_DE_DEMO.BRONZE.S3_STAGE/raw_data_stage/
    PATTERN = '.*shipments.*\\.csv';

-- Refresh pipes to load existing files
ALTER PIPE COCO_DE_DEMO.BRONZE.PIPE_CUSTOMERS REFRESH;
ALTER PIPE COCO_DE_DEMO.BRONZE.PIPE_ORDERS REFRESH;
ALTER PIPE COCO_DE_DEMO.BRONZE.PIPE_ORDER_ITEMS REFRESH;
ALTER PIPE COCO_DE_DEMO.BRONZE.PIPE_PRODUCTS REFRESH;
ALTER PIPE COCO_DE_DEMO.BRONZE.PIPE_PAYMENTS REFRESH;
ALTER PIPE COCO_DE_DEMO.BRONZE.PIPE_SHIPMENTS REFRESH;
