-- ============================================================
-- 09: Object Tagging & Tag Propagation
-- Governance tags across Bronze / Silver / Gold layers
-- ============================================================

-- ============================================================
-- TAGS: Created by DCM in COCO_DE_DEMO.DCM schema
-- (No need to CREATE — DCM deploy handles tag creation)
-- ============================================================


-- ============================================================
-- BRONZE TABLE TAGS
-- ============================================================

ALTER TABLE COCO_DE_DEMO.BRONZE.CUSTOMERS SET TAG
  COCO_DE_DEMO.DCM.PIPELINE_LAYER = 'BRONZE',
  COCO_DE_DEMO.DCM.DATA_CLASSIFICATION = 'CONFIDENTIAL',
  COCO_DE_DEMO.DCM.DATA_DOMAIN = 'CUSTOMER',
  COCO_DE_DEMO.DCM.QUALITY_TIER = 'RAW';

ALTER TABLE COCO_DE_DEMO.BRONZE.ORDERS SET TAG
  COCO_DE_DEMO.DCM.PIPELINE_LAYER = 'BRONZE',
  COCO_DE_DEMO.DCM.DATA_CLASSIFICATION = 'INTERNAL',
  COCO_DE_DEMO.DCM.DATA_DOMAIN = 'ORDER',
  COCO_DE_DEMO.DCM.QUALITY_TIER = 'RAW';

ALTER TABLE COCO_DE_DEMO.BRONZE.ORDER_ITEMS SET TAG
  COCO_DE_DEMO.DCM.PIPELINE_LAYER = 'BRONZE',
  COCO_DE_DEMO.DCM.DATA_CLASSIFICATION = 'INTERNAL',
  COCO_DE_DEMO.DCM.DATA_DOMAIN = 'ORDER',
  COCO_DE_DEMO.DCM.QUALITY_TIER = 'RAW';

ALTER TABLE COCO_DE_DEMO.BRONZE.PRODUCTS SET TAG
  COCO_DE_DEMO.DCM.PIPELINE_LAYER = 'BRONZE',
  COCO_DE_DEMO.DCM.DATA_CLASSIFICATION = 'INTERNAL',
  COCO_DE_DEMO.DCM.DATA_DOMAIN = 'PRODUCT',
  COCO_DE_DEMO.DCM.QUALITY_TIER = 'RAW';

ALTER TABLE COCO_DE_DEMO.BRONZE.PAYMENTS SET TAG
  COCO_DE_DEMO.DCM.PIPELINE_LAYER = 'BRONZE',
  COCO_DE_DEMO.DCM.DATA_CLASSIFICATION = 'CONFIDENTIAL',
  COCO_DE_DEMO.DCM.DATA_DOMAIN = 'PAYMENT',
  COCO_DE_DEMO.DCM.QUALITY_TIER = 'RAW';

ALTER TABLE COCO_DE_DEMO.BRONZE.SHIPMENTS SET TAG
  COCO_DE_DEMO.DCM.PIPELINE_LAYER = 'BRONZE',
  COCO_DE_DEMO.DCM.DATA_CLASSIFICATION = 'INTERNAL',
  COCO_DE_DEMO.DCM.DATA_DOMAIN = 'SHIPMENT',
  COCO_DE_DEMO.DCM.QUALITY_TIER = 'RAW';


-- ============================================================
-- SILVER TABLE TAGS
-- ============================================================

ALTER TABLE COCO_DE_DEMO.SILVER.STG_CUSTOMERS SET TAG
  COCO_DE_DEMO.DCM.PIPELINE_LAYER = 'SILVER',
  COCO_DE_DEMO.DCM.DATA_CLASSIFICATION = 'CONFIDENTIAL',
  COCO_DE_DEMO.DCM.DATA_DOMAIN = 'CUSTOMER',
  COCO_DE_DEMO.DCM.QUALITY_TIER = 'VALIDATED';

ALTER TABLE COCO_DE_DEMO.SILVER.STG_ORDERS SET TAG
  COCO_DE_DEMO.DCM.PIPELINE_LAYER = 'SILVER',
  COCO_DE_DEMO.DCM.DATA_CLASSIFICATION = 'INTERNAL',
  COCO_DE_DEMO.DCM.DATA_DOMAIN = 'ORDER',
  COCO_DE_DEMO.DCM.QUALITY_TIER = 'VALIDATED';

ALTER TABLE COCO_DE_DEMO.SILVER.STG_ORDER_ITEMS SET TAG
  COCO_DE_DEMO.DCM.PIPELINE_LAYER = 'SILVER',
  COCO_DE_DEMO.DCM.DATA_CLASSIFICATION = 'INTERNAL',
  COCO_DE_DEMO.DCM.DATA_DOMAIN = 'ORDER',
  COCO_DE_DEMO.DCM.QUALITY_TIER = 'VALIDATED';

ALTER TABLE COCO_DE_DEMO.SILVER.STG_PRODUCTS SET TAG
  COCO_DE_DEMO.DCM.PIPELINE_LAYER = 'SILVER',
  COCO_DE_DEMO.DCM.DATA_CLASSIFICATION = 'INTERNAL',
  COCO_DE_DEMO.DCM.DATA_DOMAIN = 'PRODUCT',
  COCO_DE_DEMO.DCM.QUALITY_TIER = 'VALIDATED';

ALTER TABLE COCO_DE_DEMO.SILVER.STG_PAYMENTS SET TAG
  COCO_DE_DEMO.DCM.PIPELINE_LAYER = 'SILVER',
  COCO_DE_DEMO.DCM.DATA_CLASSIFICATION = 'CONFIDENTIAL',
  COCO_DE_DEMO.DCM.DATA_DOMAIN = 'PAYMENT',
  COCO_DE_DEMO.DCM.QUALITY_TIER = 'VALIDATED';

ALTER TABLE COCO_DE_DEMO.SILVER.STG_SHIPMENTS SET TAG
  COCO_DE_DEMO.DCM.PIPELINE_LAYER = 'SILVER',
  COCO_DE_DEMO.DCM.DATA_CLASSIFICATION = 'INTERNAL',
  COCO_DE_DEMO.DCM.DATA_DOMAIN = 'SHIPMENT',
  COCO_DE_DEMO.DCM.QUALITY_TIER = 'VALIDATED';


-- ============================================================
-- GOLD TABLE TAGS
-- ============================================================

ALTER TABLE COCO_DE_DEMO.GOLD.DIM_CUSTOMERS SET TAG
  COCO_DE_DEMO.DCM.PIPELINE_LAYER = 'GOLD',
  COCO_DE_DEMO.DCM.DATA_CLASSIFICATION = 'CONFIDENTIAL',
  COCO_DE_DEMO.DCM.DATA_DOMAIN = 'CUSTOMER',
  COCO_DE_DEMO.DCM.QUALITY_TIER = 'CERTIFIED';

ALTER TABLE COCO_DE_DEMO.GOLD.DIM_PRODUCTS SET TAG
  COCO_DE_DEMO.DCM.PIPELINE_LAYER = 'GOLD',
  COCO_DE_DEMO.DCM.DATA_CLASSIFICATION = 'INTERNAL',
  COCO_DE_DEMO.DCM.DATA_DOMAIN = 'PRODUCT',
  COCO_DE_DEMO.DCM.QUALITY_TIER = 'CERTIFIED';

ALTER TABLE COCO_DE_DEMO.GOLD.FACT_SALES SET TAG
  COCO_DE_DEMO.DCM.PIPELINE_LAYER = 'GOLD',
  COCO_DE_DEMO.DCM.DATA_CLASSIFICATION = 'CONFIDENTIAL',
  COCO_DE_DEMO.DCM.DATA_DOMAIN = 'ORDER',
  COCO_DE_DEMO.DCM.QUALITY_TIER = 'CERTIFIED';

ALTER TABLE COCO_DE_DEMO.GOLD.DIM_DATES SET TAG
  COCO_DE_DEMO.DCM.PIPELINE_LAYER = 'GOLD',
  COCO_DE_DEMO.DCM.DATA_CLASSIFICATION = 'PUBLIC',
  COCO_DE_DEMO.DCM.DATA_DOMAIN = 'ORDER',
  COCO_DE_DEMO.DCM.QUALITY_TIER = 'CERTIFIED';

ALTER TABLE COCO_DE_DEMO.GOLD.FACT_SHIPMENT_PERFORMANCE SET TAG
  COCO_DE_DEMO.DCM.PIPELINE_LAYER = 'GOLD',
  COCO_DE_DEMO.DCM.DATA_CLASSIFICATION = 'INTERNAL',
  COCO_DE_DEMO.DCM.DATA_DOMAIN = 'SHIPMENT',
  COCO_DE_DEMO.DCM.QUALITY_TIER = 'CERTIFIED';

ALTER TABLE COCO_DE_DEMO.GOLD.FACT_PAYMENT_SUMMARY SET TAG
  COCO_DE_DEMO.DCM.PIPELINE_LAYER = 'GOLD',
  COCO_DE_DEMO.DCM.DATA_CLASSIFICATION = 'CONFIDENTIAL',
  COCO_DE_DEMO.DCM.DATA_DOMAIN = 'PAYMENT',
  COCO_DE_DEMO.DCM.QUALITY_TIER = 'CERTIFIED';

ALTER TABLE COCO_DE_DEMO.GOLD.FACT_DAILY_REVENUE SET TAG
  COCO_DE_DEMO.DCM.PIPELINE_LAYER = 'GOLD',
  COCO_DE_DEMO.DCM.DATA_CLASSIFICATION = 'INTERNAL',
  COCO_DE_DEMO.DCM.DATA_DOMAIN = 'ORDER',
  COCO_DE_DEMO.DCM.QUALITY_TIER = 'CERTIFIED';


-- ============================================================
-- PII COLUMN TAGS - Bronze
-- ============================================================

ALTER TABLE COCO_DE_DEMO.BRONZE.CUSTOMERS MODIFY COLUMN EMAIL
  SET TAG COCO_DE_DEMO.DCM.PII = 'TRUE';
ALTER TABLE COCO_DE_DEMO.BRONZE.CUSTOMERS MODIFY COLUMN PHONE
  SET TAG COCO_DE_DEMO.DCM.PII = 'TRUE';
ALTER TABLE COCO_DE_DEMO.BRONZE.CUSTOMERS MODIFY COLUMN FIRST_NAME
  SET TAG COCO_DE_DEMO.DCM.PII = 'TRUE';
ALTER TABLE COCO_DE_DEMO.BRONZE.CUSTOMERS MODIFY COLUMN LAST_NAME
  SET TAG COCO_DE_DEMO.DCM.PII = 'TRUE';


-- ============================================================
-- PII COLUMN TAGS - Silver
-- ============================================================

ALTER TABLE COCO_DE_DEMO.SILVER.STG_CUSTOMERS MODIFY COLUMN EMAIL
  SET TAG COCO_DE_DEMO.DCM.PII = 'TRUE';
ALTER TABLE COCO_DE_DEMO.SILVER.STG_CUSTOMERS MODIFY COLUMN PHONE
  SET TAG COCO_DE_DEMO.DCM.PII = 'TRUE';
ALTER TABLE COCO_DE_DEMO.SILVER.STG_CUSTOMERS MODIFY COLUMN FIRST_NAME
  SET TAG COCO_DE_DEMO.DCM.PII = 'TRUE';
ALTER TABLE COCO_DE_DEMO.SILVER.STG_CUSTOMERS MODIFY COLUMN LAST_NAME
  SET TAG COCO_DE_DEMO.DCM.PII = 'TRUE';


-- ============================================================
-- PII COLUMN TAGS - Gold
-- ============================================================

ALTER TABLE COCO_DE_DEMO.GOLD.DIM_CUSTOMERS MODIFY COLUMN EMAIL
  SET TAG COCO_DE_DEMO.DCM.PII = 'TRUE';
ALTER TABLE COCO_DE_DEMO.GOLD.DIM_CUSTOMERS MODIFY COLUMN FIRST_NAME
  SET TAG COCO_DE_DEMO.DCM.PII = 'TRUE';
ALTER TABLE COCO_DE_DEMO.GOLD.DIM_CUSTOMERS MODIFY COLUMN LAST_NAME
  SET TAG COCO_DE_DEMO.DCM.PII = 'TRUE';


-- ============================================================
-- VERIFICATION QUERIES
-- ============================================================

-- Verify PII tag references on Bronze customers
-- SELECT TAG_NAME, TAG_VALUE, COLUMN_NAME
-- FROM TABLE(COCO_DE_DEMO.INFORMATION_SCHEMA.TAG_REFERENCES_ALL_COLUMNS(
--   'COCO_DE_DEMO.BRONZE.CUSTOMERS', 'TABLE'))
-- WHERE TAG_NAME = 'PII';

-- Verify table-level tags
-- SELECT TAG_NAME, TAG_VALUE
-- FROM TABLE(COCO_DE_DEMO.INFORMATION_SCHEMA.TAG_REFERENCES(
--   'COCO_DE_DEMO.GOLD.DIM_CUSTOMERS', 'TABLE'))
-- ORDER BY TAG_NAME;
